const obj = [
  {
    buyerName: "Mayur",
    buyerAddress: "Rajkot",
    sellerOne: {
      layoutType: "layout1",
      name: "sellerOne",
      address: "sellerOne Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
    sellerTwo: {
      layoutType: "layout2",
      name: "sellerTwo",
      address: "sellerTwo Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
    sellerThree: {
      layoutType: "layout3",
      name: "sellerThree",
      address: "sellerThree Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
  },
  {
    buyerName: "PDC",
    buyerAddress: "Amdbd",
    sellerOne: {
      layoutType: "layout1",
      name: "PDC-1",
      address: "PDC-1 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
    sellerTwo: {
      layoutType: "layout2",
      name: "PDC-2",
      address: "PDC-2 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
    sellerThree: {
      layoutType: "layout3",
      name: "PDC-3",
      address: "PDC-3 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
  },
  {
    buyerName: "PDC-2",
    buyerAddress: "Amdbd",
    sellerOne: {
      layoutType: "layout1",
      name: "PDC-1",
      address: "PDC-1 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
    sellerTwo: {
      layoutType: "layout2",
      name: "PDC-2",
      address: "PDC-2 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
    sellerThree: {
      layoutType: "layout3",
      name: "PDC-3",
      address: "PDC-3 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
  },
  {
    buyerName: "PDC-3",
    buyerAddress: "Amdbd",
    sellerOne: {
      layoutType: "layout1",
      name: "PDC-1",
      address: "PDC-1 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
    sellerTwo: {
      layoutType: "layout2",
      name: "PDC-2",
      address: "PDC-2 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
    sellerThree: {
      layoutType: "layout3",
      name: "PDC-3",
      address: "PDC-3 Address",
      total: "",
      invoiceNoPrefix: "",
      invoiceNoStart: "",
      invoiceNoAdd: "",
      dateStart: "",
      noOfParticulars: "",
      data: {
        particulars: [],
        rate: [],
      },
    },
  },
];

export function setData() {
  localStorage.setItem("home", JSON.stringify(obj));
}
export function getData() {
  const data = JSON.parse(localStorage.getItem("home"));
  return data;
}
