import type { buyer } from "../Models/buyer";

export const dummyBuyers: buyer[] = [
  {
    buyerName: "John's Hardware Store",
    buyerAddress: "123 Main St, Anytown, USA",
    type: "Retail",
    seller1: {
      layoutType: "layout1",
      name: "ABC Suppliers",
      address: "456 Supplier Ave, Industry Park",
      total: "$1,234.56",
      invoiceNoPrefix: "INV",
      invoiceNoStart: "1001",
      invoiceNoAdd: "1",
      dateStart: "2025-07-01",
      noOfParticulars: "5",
      data: {
        particulars: [
          "Hammer",
          "Screwdriver Set",
          "Pliers",
          "Wrench",
          "Tape Measure",
        ],
        rate: ["15.99", "24.99", "12.50", "9.99", "7.99"],
      },
      invoiceData: [],
    },
    seller2: {
      layoutType: "layout2",
      name: "XYZ Tools",
      address: "789 Tool Ln, Workshop City",
      total: "$876.54",
      invoiceNoPrefix: "ORD",
      invoiceNoStart: "2001",
      invoiceNoAdd: "1",
      dateStart: "2025-07-15",
      noOfParticulars: "3",
      data: {
        particulars: ["Power Drill", "Circular Saw", "Sander"],
        rate: ["129.99", "149.99", "89.99"],
      },
      invoiceData: [],
    },
    seller3: {
      layoutType: "layout3",
      name: "Global Hardware",
      address: "321 International Blvd, Trade Center",
      total: "$2,345.67",
      invoiceNoPrefix: "GH",
      invoiceNoStart: "3001",
      invoiceNoAdd: "1",
      dateStart: "2025-07-20",
      noOfParticulars: "4",
      data: {
        particulars: ["Ladder", "Toolbox Set", "Workbench", "Safety Gear"],
        rate: ["199.99", "159.99", "249.99", "89.99"],
      },
      invoiceData: [],
    },
  },
  {
    buyerName: "Jane's Home Improvement",
    buyerAddress: "789 Oak St, Somewhere City",
    type: "Wholesale",
    seller1: {
      layoutType: "layout2",
      name: "Home Pro Supplies",
      address: "555 Contractor Rd, Industrial Zone",
      total: "$3,210.98",
      invoiceNoPrefix: "HP",
      invoiceNoStart: "4001",
      invoiceNoAdd: "1",
      dateStart: "2025-07-10",
      noOfParticulars: "6",
      data: {
        particulars: [
          "Paint Brushes",
          "Rollers",
          "Paint Trays",
          "Drop Cloths",
          "Painters Tape",
          "Sandpaper",
        ],
        rate: ["8.99", "12.99", "5.99", "14.99", "7.99", "3.99"],
      },
      invoiceData: [],
    },
    seller2: {
      layoutType: "layout1",
      name: "Flooring Experts",
      address: "222 Hardwood Dr, Flooring District",
      total: "$4,567.89",
      invoiceNoPrefix: "FE",
      invoiceNoStart: "5001",
      invoiceNoAdd: "1",
      dateStart: "2025-07-05",
      noOfParticulars: "3",
      data: {
        particulars: ["Hardwood Flooring", "Underlayment", "Baseboards"],
        rate: ["3.99", "0.99", "2.49"],
      },
      invoiceData: [],
    },
    seller3: {
      layoutType: "layout3",
      name: "Lighting World",
      address: "777 Bright St, Lighting District",
      total: "$1,234.56",
      invoiceNoPrefix: "LW",
      invoiceNoStart: "6001",
      invoiceNoAdd: "1",
      dateStart: "2025-07-18",
      noOfParticulars: "5",
      data: {
        particulars: [
          "Ceiling Lights",
          "Wall Sconces",
          "Pendant Lights",
          "Chandelier",
          "LED Bulbs",
        ],
        rate: ["89.99", "45.99", "79.99", "199.99", "8.99"],
      },
      invoiceData: [],
    },
  },
];
